#!/bin/sh
#
case "$1" in
  start)
	printf "Setting up IP Routing and Forwarding: "
	sysctl -w net.ipv4.ip_forward=1
	iptables-restore < /etc/iptables.conf




	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping Router: "
	
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
