#!/bin/sh
#
case "$1" in
  start)
	printf "Starting VLAN on eth1: "
	vconfig add eth1 10
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Removing VLAN on eth1: "
	vconfig rem eth1.10
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
