#!/bin/sh
#
case "$1" in
  start)
	printf "Starting WiFi AP: "
	start-stop-daemon -S -b -p /var/run/hostapd.pid --exec /usr/sbin/hostapd /etc/hostapd.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Shutting down WiFi AP: "
	start-stop-daemon -K -p /var/run/hostapd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
